// DARK GAME Card Pools — Bilingual (JP/ZH + EN)

const cardPools = {
    pool: [
        ["無下限術式.赫 (短距離傳送)(三回合一次)(特殊)(S)", "Cursed Technique: Red (Short-range teleport)(Once per 3 turns)(Special)(S)"],
        ["無下限術式.蒼 (超強化體術)(反應力永久強化)(特殊)(S)", "Cursed Technique: Blue (Enhanced martial arts)(Permanent reaction boost)(Special)(S)"],
        ["反轉術式 (A)（只能修復小傷，斷肢需兩回合）", "Reverse Cursed Technique (A)(Minor injuries only, dismemberment takes 2 turns)"],
        ["黑閃 (A)（普通傷害的平方倍）", "Black Flash (A)(Damage squared)"],
        ["十畫咒法 (B)（弱點攻擊）", "Ten Shadows Technique (B)(Critical hit)"],
        ["詛咒惡魔 (A)（詛咒對手一個負面效果，共三次）", "Curse Devil (A)(Curse opponent with debuff, 3 times)"],
        ["石化惡魔 (A)（石化對手一回合，冷卻五回合）", "Petrification Devil (A)(Petrify opponent 1 turn, 5 turn cooldown)"],
        ["狐狸惡魔 (B)", "Fox Devil (B)"],
        ["十種影法術 (S)", "Ten Shadow Magic (S)"],
        ["熔岩", "Lava"],
        ["黑繩（阻斷能力，五回合內燃盡）", "Divine Void Chain (Disables ability for 5 turns)"],
        ["蜘蛛人2099", "Spider-Man 2099"],
        ["海水", "Seawater"],
        ["閃光", "Flash"],
        ["雷電", "Lightning"],
        ["創造（基礎金屬與元素）", "Creation (Basic metals and elements)"],
        ["絲線", "String"],
        ["火焰", "Fire"],
        ["神的不在場證明（三回合隱身，冷卻兩回合）", "Divine Empty Alibi (Invisible 3 turns, 2 turn cooldown)"],
        ["第三代火焰能力者（熱空氣、電波、惡魔火）", "Third Generation Flame User (Hot air, radio waves, Devil fire)"],
        ["瞬間移動（兩回合一次）", "Teleport (Once per 2 turns)"],
        ["複製（複製對手能力一次，最多兩次）", "Copy (Copy opponent ability once, max twice)"],
        ["爆炸", "Explosion"],
        ["時間暫停（三次）", "Time Stop (3 uses)"],
        ["四次元公寓（兩回合躲藏，冷卻三回合）", "4D Apartment (Hide 2 turns, 3 turn cooldown)"],
        ["血輪眼（進化會失去能力與武器）", "Sharingan (Evolution loses ability and weapon)"],
        ["吸血（依傷口吸取）", "Blood Drain (Base on wound size)"],
        ["生命偷取（少量）", "Life Steal (Minor)"],
        ["植物", "Plant"],
        ["東堂的拍手術式", "Todo's Open-Hand Technique"],
        ["暗影大人史萊姆（一次核爆）", "Shadow Lord Slime (One nuclear explosion)"],
        ["惠惠的爆裂魔法（兩次，用後疲勞）", "Megumin's Explosion (2 uses, then fatigue)"],
        ["神盾（免疫攻擊一回合，冷卻三回合）", "Divine Shield (Immune to attack 1 turn, 3 turn cooldown)"],
        ["死靈法術（召喚死靈軍隊）", "Necromancy (Summon undead army)"],
        ["犧牲召喚（召喚基礎能力，五次）", "Sacrifice Summon (Summon basic ability, 5 uses)"],
        ["模仿（體術動作，不含能力）", "Mimicry (Copy physical moves, not abilities)"],
        ["超再生（斷肢三回合恢復，冷卻三回合）", "Super Regeneration (Limb recovery 3 turns, 3 turn cooldown)"],
        ["風", "Wind"],
        ["火", "Fire"],
        ["水", "Water"],
        ["雷", "Lightning"],
        ["土", "Earth"],
        ["冰", "Ice"],
        ["太陽", "Sun"],
        ["水晶", "Crystal"],
        ["鋼", "Steel"],
        ["One for All", "One for All"],
        ["All for One", "All for One"],
        ["逕庭拳（延遲自動再攻擊）", "Faux Leg Strike (Delayed auto-attack)"],
        ["延遲傷害（下一回合才造成傷害）", "Delayed Damage (Damage dealt next turn)"],
        ["咒靈操術", "Curse Manipulation"],
        ["全反擊（物理攻擊反擊一次）", "Full Counter (Counter physical attack once)"],
        ["PLANT//SHAPER（隕石、傳送門，冷卻五回合）", "PLANT//SHAPER (Meteor, portal, 5 turn cooldown)"],
        ["赤血操術（需流血）", "Blood Control (Requires bleeding)"],
        ["必須能呼 (S)", "Must Be Able To (S)"],
        ["惡魔體（免疫物理攻擊，自我修復）", "Demon Body (Immune to physical, self-repair)"],
        ["波紋", "Ripple"],
        ["蜈蚣赫子", "Centipede赫子"],
        ["羽赫", "Feather赫"],
        ["Xeno梟赫子", "Xeno枭赫子"],
        ["螺旋丸", "Spiral Sphere"],
        ["神威（三回合一次）", "Kamui (Once per 3 turns)"],
        ["幻術（三回合冷卻）", "Illusion (3 turn cooldown)"],
        ["召喚幫手（現實人物）", "Summon Helper (Real-life person)"],
        ["始解", "Shikai"],
        ["卍解", "Bankai"],
        ["黑霧", "Black Mist"],
        ["死亡回歸（兩次）", "Death Loop (2 uses)"],
        ["煙幕", "Smokescreen"],
        ["無限長繩子", "Infinite Rope"],
        ["沙德威斯坦（兩回合，之後當機一回合）", "Saudiswtan (2 turns, then crash 1 turn)"],
        ["程式駭入", "Program Hack"],
        ["王子戰法", "Prince's Strategy"],
        ["元氣彈", "Spirit Bomb"],
        ["加力炮", "Galick Gun"],
        ["龜派氣功", "Kamehameha"],
        ["毀滅（三次）", "Annihilate (3 uses)"],
        ["抹消（五次）", "Erase (5 uses)"],
        ["奈米科技", "Nanotechnology"],
        ["無人機控制", "Drone Control"],
        ["金正恩（核彈與北韓軍隊）", "Kim Jong-un (Nuclear bomb and army)"],
        ["習近平（核彈與共軍）", "Xi Jinping (Nuclear bomb and army)"],
        ["投影咒法", "Projection Curse"],
        ["咒言（語言越強自損越多）", "Curse Word (Stronger words more self-damage)"],
        ["毒", "Poison"],
        ["仙人跳", "Trap"],
        ["瞬步", "Flash Step"],
        ["剃（兩回合一次）", "Sundome (Once per 2 turns)"],
        ["月牙天衝", "Getsuga Tenshou"],
        ["聖文字（BLEACH）", "Holy Letter (BLEACH)"],
        ["月亮", "Moon"],
        ["日蝕", "Eclipse"],
        ["特殊召喚", "Special Summon"],
        ["轉生", "Reincarnation"],
        ["嘴炮（心靈）", "Trash Talk (Mind)"],
        ["嘴炮（物理）", "Trash Talk (Physical)"],
        ["酸", "Acid"],
        ["氣彈", "Energy Blast"],
        ["黏黏球", "Goo Ball"],
        ["立場屏障（兩回合物理有效）", "Force Field (Physical effective 2 turns)"],
        ["迷因攻擊", "Meme Attack"],
        ["念動力（不能撕裂）", "Psychokinesis (Cannot tear)"],
        ["Sans", "Sans"],
        ["液態氮", "Liquid Nitrogen"],
        ["速度與激情", "Fast and Furious"],
        ["武裝色", "Armament Haki"],
        ["死靈召喚", "Necromancy Summon"],
        ["神之義眼", "Divine Ancestral Eye"],
        ["半冷半熱", "Half Cold Half Hot"],
        ["虛閃", "Cero"],
        ["惡靈:夢境惡靈", "Evil Spirit: Dream Spirit"],
        ["惡靈:力量惡靈", "Evil Spirit: Power Spirit"],
        ["惡靈:死亡惡靈", "Evil Spirit: Death Spirit"],
        ["惡靈:黑暗惡靈", "Evil Spirit: Darkness Spirit"],
        ["惡靈:感官控制惡靈", "Evil Spirit: Sense Control Spirit"],
        ["想像力(聖文字)", "Imagination (Holy Letter)"],
        ["惡魔果實:岩漿", "Devil Fruit: Magma"],
        ["惡魔果實:重力", "Devil Fruit: Gravity"],
        ["惡魔果實:閃光", "Devil Fruit: Light"],
        ["惡魔果實:幻獸不死鳥", "Devil Fruit: Phoenix"],
        ["惡魔果實:幻獸尼卡", "Devil Fruit: Nika"],
        ["惡魔果實:暗暗", "Devil Fruit: Dark-Dark"],
        ["惡魔果實:四分五裂", "Devil Fruit: Chop-Chop"],
        ["惡魔果實:冰冰", "Devil Fruit: Ice-Ice"],
        ["惡魔果實:震震", "Devil Fruit: Quake-Quake"],
        ["惡魔果實:大佛", "Devil Fruit: Buddha"],
        ["聖文字:對立", "Schrift: Oppose"],
        ["聖文字:調和", "Schrift: Balance"],
        ["聖文字:強制執行", "Schrift: Enforce"],
        ["聖文字:致死量", "Schrift: Lethal Dose"],
        ["聖文字:爆擊", "Schrift: Critical"],
        ["聖文字:恐懼", "Schrift: Fear"],
        ["聖文字:貪吃", "Schrift: Gluttony"],
        ["聖文字:灼熱", "Schrift: Blazing"],
        ["聖文字:鋼鐵", "Schrift: Steel"],
        ["聖文字:監獄", "Schrift: Jail"],
        ["聖文字:愛(控制)", "Schrift: Love (Control)"],
        ["聖文字:奇蹟", "Schrift: Miracle"],
        ["聖文字:虐殺", "Schrift: Slaughter"],
        ["聖文字:力量", "Schrift: Power"],
        ["聖文字:異議", "Schrift: Dissent"],
        ["聖文字:咆嘯", "Schrift: Roar"],
        ["聖文字:英雄", "Schrift: Hero"],
        ["聖文字:雷霆", "Schrift: Thunder"],
        ["聖文字:無防備", "Schrift: None-Defense"],
        ["聖文字:風", "Schrift: Wind"],
        ["聖文字:貫穿", "Schrift: Penetrate"],
        ["聖文字:模仿", "Schrift: Mimic"],
        ["聖文字:身體控制", "Schrift: Body Control"],
        ["聖文字:消失點", "Schrift: Vanishing Point"],
        ["聖文字:生命力", "Schrift: Vitality"],
        ["負面效果:流血", "Debuff: Bleed"],
        ["負面效果:凍結", "Debuff: Freeze"],
        ["負-防禦下降", "Debuff: Defense Down"],
        ["負-易傷", "Debuff: Vulnerable"],
        ["負-行動遲緩", "Debuff: Slow"],
        ["負-觸電", "Debuff: Shock"],
        ["負-頭暈", "Debuff: Daze"],
        ["負-噁心", "Debuff: Nausea"],
        ["負-疲勞", "Debuff: Fatigue"],
        ["負-消極", "Debuff: Negative"],
        ["負-身體殘缺", "Debuff: Limb Loss"],
        ["負-感電", "Debuff: Electric"],
        ["持續傷害:流血", "DoT: Bleed"],
        ["持續傷害:凍傷", "DoT: Frostbite"],
        ["持續傷害:燃燒", "DoT: Burn"],
        ["持續傷害:觸電", "DoT: Shock"],
        ["持續傷害:頭暈", "DoT: Daze"],
        ["持續傷害:噁心", "DoT: Nausea"],
        ["持續傷害:疲勞", "DoT: Fatigue"],
        ["持續傷:行動遲緩", "DoT: Slow"],
        ["持續傷:心靈創傷", "DoT: Mind Trauma"],
        ["持續傷:身體殘缺", "DoT: Limb Loss"],
        ["持續傷:消極", "DoT: Negative"],
        ["魔虛羅", "Mahito"],
        ["替身:綠色法皇", "Stand: Green Hanged Man"],
        ["替身:白金世界", "Stand: Platinum Style"],
        ["替身:世界", "Stand: The World"],
        ["替身:瘋狂鑽石", "Stand: Crazy Diamond"],
        ["替身:黃金體驗", "Stand: Gold Experience"],
        ["替身:白蛇", "Stand: White Snake"],
        ["替身:轟炸空間", "Stand: Bomb Space"],
        ["替身:死神13", "Stand: Death 13"],
        ["替身:戀人", "Stand: Lovers"],
        ["替身:牙", "Stand: Clacker"],
        ["替身:D4C", "Stand: D4C"],
        ["替身:克林姆王", "Stand: Cream Starter"],
        ["替身:鋼鍊手指", "Stand: Rolling Stones"],
        ["替身:性感手槍", "Stand: Sex Pistols"],
        ["替身:皇帝", "Stand: Emperor"],
        ["替身:回音", "Stand: Echoes"],
        ["替身:殺手皇后", "Stand: Killer Queen"],
        ["Ben10:火焰人", "Ben10: Heatblast"],
        ["Ben10:轟天雷", "Ben10: XLR8"],
        ["Ben10:鑽石戰神", "Ben10: Diamondhead"],
        ["Ben10:寒冰幽靈", "Ben10: Ghostfreak"],
        ["Ben10:神力暴龍", "Ben10: Four Arms"],
        ["Ben10:沼澤火", "Ben10: Stinkfly"],
        ["Ben10:時鐘王", "Ben10: Clockwork"],
        ["Ben10:快閃之星", "Ben10: Fasttrack"],
        ["Ben10:變形魔", "Ben10: Jetray"],
        ["Ben10:猛爆蟲", "Ben10: Upgrade"],
        ["Ben10:克蟹蟲龍", "Ben10: Brimstone"],
        ["Ben10:叛努辛獸", "Ben10: Crabnut"],
        ["Ben10:終極寒冰幽靈", "Ben10: Ultimate Ghostfreak"],
        ["Ben10:終極神力暴龍", "Ben10: Ultimate Four Arms"],
        ["Ben10:終極沼澤火", "Ben10: Ultimate Wildvine"],
        ["Ben10:異形暴龍", "Ben10: Amphibian"],
        ["Ben10:X金剛", "Ben10: Eat"],
        ["Ben10:四手暴龍", "Ben10: Way Big"],
        ["Ben10:電蜥", "Ben10: Stinkarms"],
        ["Ben10:超巨人", "Ben10: Atomix"],
        ["Ben10:重力蟹霸", "Ben10: Bloxx"],
        ["Ben10:積木猩", "Ben10: Gravattack"],
        ["Ben10:原能金剛", "Ben10: Golem"],
        ["乙骨優太{里香}", "Okkotsu {Rika}"],
        ["T.H.E REAL MIMIC", "T.H.E REAL MIMIC"],
        ["三幻神", "Three Divine Gods"],
        ["黑暗大法師", "Dark Magician"],
        ["究級青眼白龍", "Ultimate Blue-Eyes"],
        ["宿儺.伏黑", "Sukuna. Fushiguro"],
        ["鏈鋸人[波奇塔]", "Chainsawman [Pochita]"],
        ["尾獸化", "Tailed Beast Mode"],
        ["VaN vAn 大法師", "VaN vAn Magician"],
        ["自在極易", "Easy Ultra"],
        ["牙ACT1234", "Teeth ACT1234"],
        ["迪亞哥世界", "Diego's World"],
        ["殘火太刀", "Remaining Fire Blade"],
        ["山道猴子的一生", "Shoebill's Life"],
        ["Jonh Wick[憤怒]", "John Wick [Rage]"],
        ["XZ軍團", "XZ Legion"],
        ["狀態[???]", "Status[???]"],
        ["殺手皇后.敗者食塵", "Killer Queen: Bites the Dust"],
        ["始解:冰輪丸", "Shikai: Hyourinmaru"],
        ["始解:流刃若火", "Shikai: Ryuumon Hozukimaru"],
        ["始解:雀蜂", "Shikai: Senbonzakura"],
        ["始解:花天狂骨", "Shikai: Suzumebachi"],
        ["始解:鏡花水月", "Shikai: Katen Kyokotsu"],
        ["始解:千本櫻", "Shikai: Tensa Zangetsu"],
        ["始解:飛梅", "Shikai: Zabimaru"],
        ["始解:蛇尾丸", "Shikai: Sode no Shirayuki"],
        ["始解:風死", "Shikai: Wabisuke"],
        ["始解:野曬", "Shikai: Ashisogi Jizo"],
        ["始解:疋殺地蔵", "Shikai: Soi Fon"],
        ["始解:神槍", "Shikai: Kajomari"],
        ["始解:袖白雪", "Shikai: Hakka no Togame"],
        ["始解:逆撫", "Shikai: Sogi Ougi"],
        ["始解:斷地風", "Shikai: Kinshara and butou"],
        ["始解:雙魚理", "Shikai: Hakka no Togame"],
        ["始解:雙王蛇尾丸", "Shikai: Hebitsukai no Tessei"],
        ["卍解:黑繩天譴明王", "Bankai: Konjiki Chouryuu Shinkuuou"],
        ["卍解:花天狂骨枯松心中", "Bankai: Kinshara Rikujou"],
        ["卍解:皆盡", "Bankai: Kajomari"],
        ["卍解:千本櫻景嚴", "Bankai: Senbonzakura Kageyoshi"],
        ["卍解:大紅蓮冰輪丸", "Bankai: Hakka no Togame"],
        ["卍解:逆樣邪八寶塞", "Bankai: Kinshara Rikujou"],
        ["卍解:風死絞繩", "Bankai: Kyoka Suigetsu"],
        ["卍解:觀音開紅姬改", "Bankai: Kannon"],
    ],
    racePool: [
        ["天使", "Angel"],
        ["精靈", "Elf"],
        ["機器人", "Robot"],
        ["鏈鋸人", "Chainsaw Man"],
        ["武士刀人", "Swordsman"],
        ["宇志波佐助", "Uchiha Sasuke"],
        ["宇志波鼬", "Uchiha Itachi"],
        ["宇志波止水", "Uchiha Shisui"],
        ["宇志波班", "Uchiha Madara"],
        ["宇志波帶土", "Uchiha Obito"],
        ["人類", "Human"],
        ["魚人", "Fishman"],
        ["吸血鬼", "Vampire"],
        ["魚族", "Merfolk"],
        ["龍族", "Dragon"],
        ["死神", "Shinigami"],
        ["不死族", "Undead"],
        ["五條家(行動強化)", "Gojo Clan (Action boost)"],
        ["禪院家(體術強化)", "Zenin Clan (Martial arts boost)"],
        ["青眼白龍", "Blue-Eyes White Dragon"],
        ["蜘蛛俠", "Spider-Man"],
        ["鋼鐵人", "Iron Man"],
        ["神奇女俠", "Wonder Woman"],
        ["蝙蝠俠", "Batman"],
        ["不死族", "Undead"],
        ["破壞神", "Destroyer God"],
        ["暗殺者", "Assassin"],
        ["幻影旅團", "Phantom Troupe"],
        ["死侍", "Deadpool"],
        ["獵人協會", "Hunter Association"],
        ["火影忍者", "Naruto Ninja"],
        ["高達", "Gundam"],
        ["賽亞人", "Saiyan"],
        ["超人", "Superman"],
        ["鬼族", "Oni"],
        ["強化人", "Cyborg"],
        ["神族(legand)", "God (Legend)"],
        ["兩面宿儺", "Ryomen Sukuna"],
        ["戰鬥天才", "Battle Genius"],
        ["天才劍士", "Genius Swordsman"],
        ["替身使者", "Stand User"],
        ["術師", "Cursed Energy User"],
        ["滅卻師", "Quincy"],
        ["貴族", "Noble"],
        ["怪獸", "Monster"],
        ["矮人", "Dwarf"],
        ["哥布林", "Goblin"],
        ["巨人", "Giant"],
        ["修道士", "Monk"],
        ["超聰明", "Super Genius"],
        ["訓龍者", "Dragon Tamer"],
        ["少林寺銅人", "Shaolin Warrior"],
        ["John Wick(基奴李維)", "John Wick (Keanu)"],
        ["魔術師", "Magician"],
        ["鳥人", "Wingman"],
        ["天空族", "Sky Tribe"],
        ["特殊超人類", "Special Superhuman"],
        ["范馬一族", "Fanma Family"],
        ["小丑", "Clown"],
        ["黑人", "Brotherhood"],
        ["放火", "Pyromaniac"],
        ["訓獸師", "Beast Tamer"],
        ["宅男", "Otaku"],
        ["肥宅", "Fat Otaku"],
        ["更木劍八", "Zaraki Kenpachi"],
        ["男生", "Male"],
        ["女生", "Female"],
        ["小孩", "Child"],
        ["屁孩", "Brat"],
        ["超弱的人", "Super Weak Person"],
    ],
    WeapenPool: [
        ["惡魔果實", "Devil Fruit"],
        ["炎魔刀(vergil)", "Demon Sword (Vergil)"],
        ["時空刃", "Time-Space Blade"],
        ["勝利誓約之劍", "Excalibur"],
        ["撒旦刃", "Satan Blade"],
        ["造船模擬器的錘子", "Hammer from Ship Simulator"],
        ["法杖", "Staff"],
        ["域門疆(封鎖對手一項能力20回合)", "Domain Expansion (Block one opponent ability 20 turns)"],
        ["七海的鉈刀(七海)", "Nanami's Knife"],
        ["乙骨的武士刀(乙骨)", "Okkotsu's Katana"],
        ["性轉藥水", "Gender Swap Potion"],
        ["匕首", "Dagger"],
        ["小刀", "Small Knife"],
        ["飛刀", "Flying Knife"],
        ["天鎖斬月", "Tensa Zangetsu"],
        ["拳套", "Boxing Gloves"],
        ["甩棍", "Tonfa"],
        ["雙刀流", "Dual Wield"],
        ["三刀流", "Triple Wield"],
        ["神器劍", "Divine Sword"],
        ["雙槍", "Dual Pistols"],
        ["烏茲", "Uzi"],
        ["RPG", "RPG"],
        ["噴子", "Shotgun"],
        ["雙節棍", "Nunchaku"],
        ["神之斧", "Divine Axe"],
        ["十字弩", "Crossbow"],
        ["卍", "卍"],
        ["斬魄刀", "Zanpakuto"],
        ["YAMAHA TMAX 560重機", "YAMAHA TMAX 560 Motorcycle"],
        ["求道玉", "Kyardama"],
        ["信夫的拳頭", "Nobuta's Fist"],
        ["噴火器", "Flamethrower"],
        ["手炮", "Hand Cannon"],
        ["朗基努斯之槍", "Spear of Longinus"],
        ["盾牌", "Shield"],
        ["武士刀", "Katana"],
        ["天逆牟", "Ame-no-Murakumo"],
        ["三結天盾", "Three-Pronged Shield"],
        ["三節棍", "Three-Section Staff"],
        ["馬桶塞", "Plunger"],
        ["弓", "Bow"],
    ],
    SummonPool: [
        ["黑洞(只能吸東西或人,每個黑洞存在一回合(共五次))", "Black Hole (Can only absorb things/people, one turn each, 5 total uses)"],
        ["靈鹿", "Spirit Deer"],
        ["聖誕阿公的雪橇跟坐騎", "Santa's Sleigh and Mount"],
        ["韓的麥卡倫", "Han's McLaren"],
        ["信夫的西瓜", "Nobuta's Watermelon"],
        ["精靈", "Elf"],
        ["魔法書", "Magic Book"],
        ["里香(十回合召喚一次,共持續三回合,共召喚3次(可發射咒力大砲,複製對手一樣能力並使用一次直到里香消失)(與乙骨優太搭配能變為完全體)(特殊))", "Rika (Summon once per 10 turns, lasts 3 turns, summon 3 times)(Can fire curse cannon, copy opponent ability once until Rika disappears)(Full power with Okkotsu)(Special)"],
        ["模仿者的面具(特殊)(模仿對手一個能力三回合兩次)", "Mimic Mask (Special)(Mimic opponent ability for 3 turns, 2 uses)"],
        ["太陽龍", "Sun Dragon"],
        ["遊戲王的卡片(可抽10次,種類:青眼白龍(最多抽到三張)[特殊],黑暗大法師(最多抽到5張)[特殊],死者復甦(最多抽到兩張),{歐西里斯天空龍,太陽神的翼神龍,歐貝利斯克巨神兵}[特殊],強欲之壺(多抽兩次卡,最多使用3次),落雷)", "Yu-Gi-Oh Cards (Draw 10 times, types: Blue-Eyes(max 3)[Special], Dark Magician(max 5)[Special], Revival(max 2), {Osiris Sky Dragon, Ra Sun God, Osiris Giant God}[Special], Pot of Greed(draw 2 extra cards, max 3 uses), Lightning)"],
        ["波奇塔", "Pochita"],
        ["九喇嘛", "Kurama"],
        ["傳奇寶相", "Legend Guardian"],
        ["男同寶相", "Yaoi Guardian"],
        ["日蝕龍", "Eclipse Dragon"],
        ["月亮龍", "Moon Dragon"],
        ["中國龍", "Chinese Dragon"],
        ["狗勾", "Dog"],
        ["蜜蜂龍", "Bee Dragon"],
        ["惡靈", "Evil Spirit"],
        ["女朋友", "Girlfriend"],
        ["怪獸宇宙傳送器", "Monster Universe Transmitter"],
        ["怪獸", "Monster"],
        ["傳送門的傳送槍", "Portal Gun"],
        ["充氣娃娃", "Real Doll"],
        ["恐龍狗", "Dino Dog"],
        ["怪獸:哥吉拉", "Monster: Godzilla"],
        ["怪獸:拉頓", "Monster: Rodan"],
        ["怪獸:摩斯拉", "Monster: Mothra"],
        ["怪獸:基多拉", "Monster: Ghidorah"],
    ],
};

function drawHand(lang) {
    const draw = (pool) => {
        const c = pool[Math.floor(Math.random() * pool.length)];
        return lang === 'en' ? (c[1] || c[0]) : (c[0] || c[1]);
    };
    return {
        race: draw(cardPools.racePool),
        weapon: draw(cardPools.WeapenPool),
        abilities: [draw(cardPools.pool), draw(cardPools.pool), draw(cardPools.pool)],
        entity: draw(cardPools.SummonPool),
    };
}

function generateId() {
    return Math.random().toString(36).substr(2, 9).toUpperCase();
}

function handler(req, res) {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
    if (req.method === 'OPTIONS') { res.status(200).end(); return; }
    if (req.method !== 'POST') { res.status(405).json({ error: 'Method not allowed' }); return; }

    const { roomCode, playerName, lang = 'en' } = req.body || {};

    if (!roomCode || !playerName || !playerName.trim()) {
        res.status(400).json({ error: 'roomCode, playerName required' });
        return;
    }

    const playerId = generateId();
    const hand = drawHand(lang);

    res.status(200).json({
        roomCode,
        playerId,
        hand,
        phase: 'ready',
        partyUrl: `wss://dark-game-battle.stgrass3.partykit.dev/room/${roomCode}`,
    });
}

module.exports = handler;