// Shared card pool data — fully self-contained, no relative imports from src/
export const cardPools = {
    pool: [
        ["無下限術式.赫","Cursed Technique: Red"],["無下限術式.蒼","Cursed Technique: Blue"],
        ["反轉術式","Reverse Cursed Technique"],["黑閃","Black Flash"],
        ["十畫咒法","Ten Shadows Technique"],["詛咒惡魔","Curse Devil"],
        ["石化惡魔","Petrification Devil"],["狐狸惡魔","Fox Devil"],
        ["十種影法術","Ten Shadow Magic"],["熔岩","Lava"],
        ["黑繩","Divine Void Chain"],["蜘蛛人2099","Spider-Man 2099"],
        ["海水","Seawater"],["閃光","Flash"],["雷電","Lightning"],
        ["創造","Creation"],["絲線","String"],["火焰","Fire"],
        ["神的不在場證明","Divine Empty Alibi"],["第三代火焰能力者","Third Generation Flame User"],
        ["瞬間移動","Teleport"],["複製","Copy"],["爆炸","Explosion"],
        ["時間暫停","Time Stop"],["四次元公寓","4D Apartment"],
        ["血輪眼","Sharingan"],["吸血","Blood Drain"],["生命偷取","Life Steal"],
        ["植物","Plant"],["東堂的拍手術式","Todo's Open-Hand Technique"],
        ["暗影大人史萊姆","Shadow Lord Slime"],["惠惠的爆裂魔法","Megumin's Explosion"],
        ["神盾","Divine Shield"],["死靈法術","Necromancy"],["犧牲召喚","Sacrifice Summon"],
        ["模仿","Mimicry"],["超再生","Super Regeneration"],
        ["風","Wind"],["火","Fire"],["水","Water"],["雷","Lightning"],
        ["土","Earth"],["冰","Ice"],["太陽","Sun"],["水晶","Crystal"],["鋼","Steel"],
        ["One for All","One for All"],["All for One","All for One"],
        ["逕庭拳","Faux Leg Strike"],["延遲傷害","Delayed Damage"],
        ["咒靈操術","Curse Manipulation"],["全反擊","Full Counter"],
        ["PLANT//SHAPER","PLANT//SHAPER"],["赤血操術","Blood Control"],
        ["必須能呼","Must Be Able To"],["惡魔體","Demon Body"],
        ["波紋","Ripple"],["蜈蚣赫子","Centipede赫子"],
        ["羽赫","Feather赫"],["Xeno梟赫子","Xeno枭赫子"],
        ["螺旋丸","Spiral Sphere"],["神威","Kamui"],["幻術","Illusion"],
        ["召喚幫手","Summon Helper"],["始解","Shikai"],["卍解","Bankai"],
        ["黑霧","Black Mist"],["死亡回歸","Death Loop"],["煙幕","Smokescreen"],
        ["無限長繩子","Infinite Rope"],["沙德威斯坦","Saudiswtan"],
        ["程式駭入","Program Hack"],["王子戰法","Prince's Strategy"],
        ["元氣彈","Spirit Bomb"],["加力炮","Galick Gun"],
        ["龜派氣功","Kamehameha"],["毀滅","Annihilate"],["抹消","Erase"],
        ["奈米科技","Nanotechnology"],["無人機控制","Drone Control"],
        ["金正恩","Kim Jong-un"],["習近平","Xi Jinping"],
        ["投影咒法","Projection Curse"],["咒言","Curse Word"],
        ["毒","Poison"],["仙人跳","Trap"],["瞬步","Flash Step"],
        ["剃","Sundome"],["月牙天衝","Getsuga Tenshou"],
        ["聖文字","Holy Letter"],["月亮","Moon"],["日蝕","Eclipse"],
        ["特殊召喚","Special Summon"],["轉生","Reincarnation"],
        ["嘴炮","Trash Talk"],["酸","Acid"],["氣彈","Energy Blast"],
        ["黏黏球","Goo Ball"],["立場屏障","Force Field"],
        ["迷因攻擊","Meme Attack"],["念動力","Psychokinesis"],
        ["Sans","Sans"],["液態氮","Liquid Nitrogen"],
        ["速度與激情","Fast and Furious"],["武裝色","Armament Haki"],
        ["死靈召喚","Necromancy Summon"],["神之義眼","Divine Ancestral Eye"],
        ["半冷半熱","Half Cold Half Hot"],["虛閃","Cero"],
        ["惡靈","Evil Spirit"],["想像力","Imagination"],
        ["負面效果:流血","Debuff: Bleed"],["負面效果:凍結","Debuff: Freeze"],
        ["持續傷害:流血","DoT: Bleed"],["持續傷害:凍傷","DoT: Frostbite"],
        ["持續傷害:燃燒","DoT: Burn"],["持續傷害:觸電","DoT: Shock"],
        ["魔虛羅","Mahito"],["替身:世界","Stand: The World"],
        ["替身:白金世界","Stand: Platinum Style"],
        ["替身:瘋狂鑽石","Stand: Crazy Diamond"],
        ["替身:黃金體驗","Stand: Gold Experience"],
        ["替身:白蛇","Stand: White Snake"],
        ["替身:轟炸空間","Stand: Bomb Space"],
        ["替身:殺手皇后","Stand: Killer Queen"],
        ["T.H.E REAL MIMIC","T.H.E REAL MIMIC"],
        ["三幻神","Three Divine Gods"],["黑暗大法師","Dark Magician"],
        ["究級青眼白龍","Ultimate Blue-Eyes"],
        ["宿儺.伏黑","Sukuna. Fushiguro"],
        ["鏈鋸人","Chainsawman"],["尾獸化","Tailed Beast Mode"],
        ["VaN vAn 大法師","VaN vAn Magician"],
        ["自在極易","Easy Ultra"],
        ["Ben10:火焰人","Ben10: Heatblast"],
        ["Ben10:轟天雷","Ben10: XLR8"],
        ["Ben10:重力蟹霸","Ben10: Bloxx"],
        ["乙骨優太{里香}","Okkotsu {Rika}"],
    ],
    racePool: [
        ["天使","Angel"],["精靈","Elf"],["機器人","Robot"],
        ["鏈鋸人","Chainsaw Man"],["武士刀人","Swordsman"],
        ["宇志波佐助","Uchiha Sasuke"],["宇志波鼬","Uchiha Itachi"],
        ["人類","Human"],["魚人","Fishman"],["吸血鬼","Vampire"],
        ["魚族","Merfolk"],["龍族","Dragon"],["死神","Shinigami"],
        ["不死族","Undead"],["五條家","Gojo Clan"],
        ["禪院家","Zenin Clan"],["強化人","Cyborg"],
        ["神族","God"],["兩面宿儺","Ryomen Sukuna"],
        ["賽亞人","Saiyan"],["超人","Superman"],["鬼族","Oni"],
        ["羅莉控","Lolicon"],["屁孩","Brat"],
        ["超弱的人","Super Weak Person"],["天才劍士","Genius Swordsman"],
        ["更木劍八","Zaraki Kenpachi"],
    ],
    WeapenPool: [
        ["炎魔刀","Demon Sword"],["時空刃","Time-Space Blade"],
        ["勝利誓約之劍","Excalibur"],["撒旦刃","Satan Blade"],
        ["法杖","Staff"],["域門疆","Domain Expansion"],
        ["七海的鉈刀","Nanami's Knife"],
        ["乙骨的武士刀","Okkotsu's Katana"],
        ["性轉藥水","Gender Swap Potion"],["匕首","Dagger"],
        ["小刀","Small Knife"],["飛刀","Flying Knife"],
        ["天鎖斬月","Tensa Zangetsu"],["拳套","Boxing Gloves"],
        ["甩棍","Tonfa"],["雙刀流","Dual Wield"],
        ["三刀流","Triple Wield"],["神器劍","Divine Sword"],
        ["雙槍","Dual Pistols"],["烏茲","Uzi"],["RPG","RPG"],
        ["噴子","Shotgun"],["雙節棍","Nunchaku"],
        ["神之斧","Divine Axe"],["十字弩","Crossbow"],
        ["斬魄刀","Zanpakuto"],["求道玉","Kyardama"],
        ["信夫的拳頭","Nobuta's Fist"],["噴火器","Flamethrower"],
        ["手炮","Hand Cannon"],["朗基努斯之槍","Spear of Longinus"],
        ["盾牌","Shield"],["武士刀","Katana"],
        ["天逆牟","Ame-no-Murakumo"],["三結天盾","Three-Pronged Shield"],
        ["馬桶塞","Plunger"],["弓","Bow"],
    ],
    TalentPool: [
        ["自殘","Self-Harm"],["舔血","Blood Lick"],
        ["感電","Electric Shock"],["預知未來","Future Sight"],
        ["六眼","Six Eyes"],["呼吸法","Breathing"],
        ["黑閃","Black Flash"],["彩虹","Rainbow"],
        ["元素抵抗","Element Resistance"],["天生的強運","Natural Lucky"],
        ["詛咒","Curse"],["完美控制","Perfect Control"],
        ["極速","Extreme Speed"],["支配","Dominate"],
        ["傲慢","Arrogance"],["心靈感應","Telepathy"],
        ["心眼","Mind's Eye"],["仙人體","Sage Body"],
        ["天體","Celestial"],["不幸","Misfortune"],
        ["天與咒縛","Heavenly Restriction"],["天身的強者","Natural Strong"],
        ["鎖血","Lock HP"],["身體殘缺","Missing Limb"],["冷靜","Calm"],
        ["霸王色霸氣","Haki of the Supreme"],["超神級反應力","Super God-tier Reflexes"],
    ],
    PlacePool: [
        ["平地","Plains"],["山地","Mountains"],["台地","Plateau"],
        ["盆地","Basin"],["虛空站台","Void Platform"],["太空","Space"],
        ["火山","Volcano"],["城市","City"],["海洋","Ocean"],
        ["空島","Sky Island"],["小島","Small Island"],
        ["學校","School"],["那美剋星","Namek"],["沙漠","Desert"],
        ["沼澤","Swamp"],["火影村","Hidden Leaf Village"],
    ],
    EventPool: [
        ["隕石來襲","Meteor Strike"],["火山爆發","Volcanic Eruption"],
        ["海嘯","Tsunami"],["血月","Blood Moon"],
        ["商人","Merchant"],["無","None"],
        ["下雨","Rain"],["下酸雨","Acid Rain"],["全體縮小","Everyone Shrink"],
        ["落雷","Lightning Strike"],["殭屍危機","Zombie Crisis"],["回合縮短","Shorter Turns"],
    ],
    SummonPool: [
        ["黑洞","Black Hole"],["靈鹿","Spirit Deer"],
        ["聖誕阿公的雪橇","Santa's Sleigh"],["韓的麥卡倫","Han's McLaren"],
        ["信夫的西瓜","Nobuta's Watermelon"],["精靈","Elf"],
        ["魔法書","Magic Book"],["里香","Rika"],
        ["模仿者的面具","Mimic Mask"],["太陽龍","Sun Dragon"],
        ["波奇塔","Pochita"],["九喇嘛","Kurama"],
        ["傳奇寶相","Legend Guardian"],["男同寶相","Yaoi Guardian"],
        ["日蝕龍","Eclipse Dragon"],["月亮龍","Moon Dragon"],
        ["中國龍","Chinese Dragon"],["狗勾","Dog"],
        ["蜜蜂龍","Bee Dragon"],["惡靈","Evil Spirit"],
        ["女朋友","Girlfriend"],["怪獸","Monster"],
        ["傳送門的傳送槍","Portal Gun"],["充氣娃娃","Real Doll"],
        ["恐龍狗","Dino Dog"],["怪獸:哥吉拉","Monster: Godzilla"],
    ],
};

export type Hand = { race: string; weapon: string; abilities: [string, string, string]; entity: string };

export function drawHand(lang: string): Hand {
    const draw = (pool: string[][]) => {
        const c = pool[Math.floor(Math.random() * pool.length)];
        return lang === 'en' ? (c[1] || c[0]) : (c[0] || c[1]);
    };
    return {
        race: draw(cardPools.racePool),
        weapon: draw(cardPools.WeapenPool),
        abilities: [draw(cardPools.pool), draw(cardPools.pool), draw(cardPools.pool)] as [string, string, string],
        entity: draw(cardPools.SummonPool),
    };
}