// DARK GAME Card Pools — Bilingual (JP/ZH + EN)

const cardPools = {
    pool: [
        ["無下限術式.赫 (短距離傳送)(三回合一次)(特殊)(S)", "Cursed Technique: Red (Short-range teleport)(Once per 3 turns)(Special)(S)"],
        ["無下限術式.蒼 (超強化體術)(反應力永久強化)(特殊)(S)", "Cursed Technique: Blue (Enhanced martial arts)(Permanent reaction boost)(Special)(S)"],
        ["反轉術式 (A)（只能修復小傷，斷肢需兩回合）", "Reverse Cursed Technique (A)(Minor injuries only, dismemberment takes 2 turns)"],
        ["黑閃 (A)（普通傷害的平方倍）", "Black Flash (A)(Damage squared)"],
        ["十畫咒法 (B)（弱點攻擊）", "Ten Shadows Technique (B)(Critical hit)"],
        ["詛咒惡魔 (A)（詛咒對手一個負面效果，共三次）", "Curse Devil (A)(Curse opponent with debuff, 3 times)"],
        ["石化惡魔 (A)（石化對手一回合，冷卻五回合）", "Petrification Devil (A)(Petrify opponent 1 turn, 5 turn cooldown)"],
        ["狐狸惡魔 (B)", "Fox Devil (B)"],
        ["十種影法術 (S)", "Ten Shadow Magic (S)"],
        ["熔岩", "Lava"],
        ["黑繩（阻斷能力，五回合內燃盡）", "Divine Void Chain (Disables ability for 5 turns)"],
        ["蜘蛛人2099", "Spider-Man 2099"],
        ["海水", "Seawater"],
        ["閃光", "Flash"],
        ["雷電", "Lightning"],
        ["創造（基礎金屬與元素）", "Creation (Basic metals and elements)"],
        ["絲線", "String"],
        ["火焰", "Fire"],
        ["神盾（免疫攻擊一回合，冷卻三回合）", "Divine Shield (Immune to attack 1 turn, 3 turn cooldown)"],
        ["死靈法術（召喚死靈軍隊）", "Necromancy (Summon undead army)"],
        ["時間暫停（三次）", "Time Stop (3 uses)"],
        ["血輪眼（進化會失去能力與武器）", "Sharingan (Evolution loses ability and weapon)"],
        ["One for All", "One for All"],
        ["All for One", "All for One"],
        ["波紋", "Ripple"],
        ["螺旋丸", "Spiral Sphere"],
        ["乙骨優太{里香}", "Okkotsu {Rika}"],
        ["風", "Wind"],
        ["水", "Water"],
        ["冰", "Ice"],
        ["雷", "Lightning"],
        ["土", "Earth"],
        ["超再生（斷肢三回合恢復，冷卻三回合）", "Super Regeneration (Limb recovery 3 turns, 3 turn cooldown)"],
        ["複製（複製對手能力一次，最多兩次）", "Copy (Copy opponent ability once, max twice)"],
        ["爆炸", "Explosion"],
        ["四次元公寓（兩回合躲藏，冷卻三回合）", "4D Apartment (Hide 2 turns, 3 turn cooldown)"],
        ["瞬間移動（兩回合一次）", "Teleport (Once per 2 turns)"],
        ["惡魔體（免疫物理攻擊，自我修復）", "Demon Body (Immune to physical, self-repair)"],
        ["王子戰法", "Prince's Strategy"],
        ["元氣彈", "Spirit Bomb"],
        ["龜派氣功", "Kamehameha"],
        ["月牙天衝", "Getsuga Tenshou"],
        ["聖文字（BLEACH）", "Holy Letter (BLEACH)"],
        ["始解", "Shikai"],
        ["卍解", "Bankai"],
        ["咒靈操術", "Curse Manipulation"],
        ["全反擊（物理攻擊反擊一次）", "Full Counter (Counter physical attack once)"],
        ["神威（三回合一次）", "Kamui (Once per 3 turns)"],
        ["幻術（三回合冷卻）", "Illusion (3 turn cooldown)"],
        ["毒", "Poison"],
        ["酸", "Acid"],
        ["仙人跳", "Trap"],
        ["瞬步", "Flash Step"],
        ["剃（兩回合一次）", "Sundome (Once per 2 turns)"],
        ["呼吸法(強化身體)", "Breathing (Body enhancement)"],
        ["霸王色霸氣", "Haki of the Supreme"],
        ["武裝色", "Armament Haki"],
        ["虛閃", "Cero"],
        ["惡魔果實:岩漿", "Devil Fruit: Magma"],
        ["惡魔果實:閃光", "Devil Fruit: Light"],
        ["惡魔果實:幻獸不死鳥", "Devil Fruit: Phoenix"],
        ["惡魔果實:尼卡", "Devil Fruit: Nika"],
        ["黑霧", "Black Mist"],
        ["死亡回歸（兩次）", "Death Loop (2 uses)"],
        ["煙幕", "Smokescreen"],
        ["PLANT//SHAPER（隕石、傳送門，冷卻五回合）", "PLANT//SHAPER (Meteor, portal, 5 turn cooldown)"],
        ["沙德威斯坦（兩回合，之後當機一回合）", "Saudiswtan (2 turns, then crash 1 turn)"],
        ["程式駭入", "Program Hack"],
        ["奈米科技", "Nanotechnology"],
        ["無人機控制", "Drone Control"],
        ["念動力（不能撕裂）", "Psychokinesis (Cannot tear)"],
        [" Sans", "Sans"],
        ["液態氮", "Liquid Nitrogen"],
        ["超神級反應力", "Super God-tier Reflexes"],
        ["完美控制", "Perfect Control"],
        ["極速", "Extreme Speed"],
        ["心靈感應", "Telepathy"],
        ["心眼", "Mind's Eye"],
        ["仙人體", "Sage Body"],
        ["必須能呼 (S)", "Must Be Able To (S)"],
        ["逕庭拳（延遲自動再攻擊）", "Faux Leg Strike (Delayed auto-attack)"],
        ["延遲傷害（下一回合才造成傷害）", "Delayed Damage (Damage dealt next turn)"],
        ["延長傷害（下一回合才造成傷害）", "Delayed Damage (Damage dealt next turn)"],
        ["東堂的拍手術式", "Todo's Open-Hand Technique"],
        ["第三代火焰能力者（熱空氣、電波、惡魔火）", "Third Generation Flame User (Hot air, radio waves, Devil fire)"],
        ["神的不在場證明（三回合隱身，冷卻兩回合）", "Divine Empty Alibi (Invisible 3 turns, 2 turn cooldown)"],
        ["吸血（依傷口吸取）", "Blood Drain (Base on wound size)"],
        ["生命偷取（少量）", "Life Steal (Minor)"],
        ["植物", "Plant"],
        ["暗影大人史萊姆（一次核爆）", "Shadow Lord Slime (One nuclear explosion)"],
        ["惠惠的爆裂魔法（兩次，用後疲勞）", "Megumin's Explosion (2 uses, then fatigue)"],
        ["犧牲召喚（召喚基礎能力，五次）", "Sacrifice Summon (Summon basic ability, 5 uses)"],
        ["模仿（體術動作，不含能力）", "Mimicry (Copy physical moves, not abilities)"],
        ["赤血操術（需流血）", "Blood Control (Requires bleeding)"],
        ["龍族", "Dragon"],
        ["天使", "Angel"],
        ["精靈", "Elf"],
        ["人類", "Human"],
        ["賽亞人", "Saiyan"],
        ["超人", "Superman"],
        ["吸血鬼", "Vampire"],
        ["死神", "Shinigami"],
        ["機器人", "Robot"],
        ["強化人", "Cyborg"],
        ["兩面宿儺", "Ryomen Sukuna"],
        ["宇志波佐助", "Uchiha Sasuke"],
        ["宇志波鼬", "Uchiha Itachi"],
        ["火", "Fire"],
        ["神族(legand)", "God (Legend)"],
        ["不死族", "Undead"],
        ["蜘蛛俠", "Spider-Man"],
        ["鋼鐵人", "Iron Man"],
        ["蝙蝠俠", "Batman"],
        ["死侍", "Deadpool"],
        ["賽亞人", "Saiyan"],
        ["火影忍者", "Naruto Ninja"],
        ["高達", "Gundam"],
        ["鏈鋸人", "Chainsaw Man"],
        ["更木劍八", "Zaraki Kenpachi"],
        ["替身:世界", "Stand: The World"],
        ["替身:白金世界", "Stand: Platinum Style"],
        ["替身:瘋狂鑽石", "Stand: Crazy Diamond"],
        ["替身:黃金體驗", "Stand: Gold Experience"],
        ["替身:殺手皇后", "Stand: Killer Queen"],
        ["尾獸化", "Tailed Beast Mode"],
        ["三幻神", "Three Divine Gods"],
        ["黑暗大法師", "Dark Magician"],
        ["究級青眼白龍", "Ultimate Blue-Eyes"],
        ["T.H.E REAL MIMIC", "T.H.E REAL MIMIC"],
        ["九喇嘛", "Kurama"],
        ["波奇塔", "Pochita"],
        ["女朋友", "Girlfriend"],
    ],
    racePool: [
        ["天使", "Angel"],
        ["精靈", "Elf"],
        ["機器人", "Robot"],
        ["鏈鋸人", "Chainsaw Man"],
        ["武士刀人", "Swordsman"],
        ["宇志波佐助", "Uchiha Sasuke"],
        ["宇志波鼬", "Uchiha Itachi"],
        ["宇志波止水", "Uchiha Shisui"],
        ["宇志波班", "Uchiha Madara"],
        ["宇志波帶土", "Uchiha Obito"],
        ["人類", "Human"],
        ["魚人", "Fishman"],
        ["吸血鬼", "Vampire"],
        ["魚族", "Merfolk"],
        ["龍族", "Dragon"],
        ["死神", "Shinigami"],
        ["不死族", "Undead"],
        ["五條家(行動強化)", "Gojo Clan (Action boost)"],
        ["禪院家(體術強化)", "Zenin Clan (Martial arts boost)"],
        ["青眼白龍", "Blue-Eyes White Dragon"],
        ["蜘蛛俠", "Spider-Man"],
        ["鋼鐵人", "Iron Man"],
        ["神奇女俠", "Wonder Woman"],
        ["蝙蝠俠", "Batman"],
        ["不死族", "Undead"],
        ["破壞神", "Destroyer God"],
        ["暗殺者", "Assassin"],
        ["幻影旅團", "Phantom Troupe"],
        ["死侍", "Deadpool"],
        ["獵人協會", "Hunter Association"],
        ["火影忍者", "Naruto Ninja"],
        ["高達", "Gundam"],
        ["賽亞人", "Saiyan"],
        ["超人", "Superman"],
        ["鬼族", "Oni"],
        ["強化人", "Cyborg"],
        ["神族(legand)", "God (Legend)"],
        ["兩面宿儺", "Ryomen Sukuna"],
        ["戰鬥天才", "Battle Genius"],
        ["天才劍士", "Genius Swordsman"],
        ["替身使者", "Stand User"],
        ["術師", "Cursed Energy User"],
        ["滅卻師", "Quincy"],
        ["貴族", "Noble"],
        ["怪獸", "Monster"],
        ["矮人", "Dwarf"],
        ["哥布林", "Goblin"],
        ["巨人", "Giant"],
        ["修道士", "Monk"],
        ["超聰明", "Super Genius"],
        ["訓龍者", "Dragon Tamer"],
        ["John Wick(基奴李維)", "John Wick (Keanu)"],
        ["魔術師", "Magician"],
        ["鳥人", "Wingman"],
        ["范馬一族", "Fanma Family"],
        ["更木劍八", "Zaraki Kenpachi"],
        ["男生", "Male"],
        ["女生", "Female"],
    ],
    WeapenPool: [
        ["惡魔果實", "Devil Fruit"],
        ["炎魔刀(vergil)", "Demon Sword (Vergil)"],
        ["時空刃", "Time-Space Blade"],
        ["勝利誓約之劍", "Excalibur"],
        ["撒旦刃", "Satan Blade"],
        ["造船模擬器的錘子", "Hammer from Ship Simulator"],
        ["法杖", "Staff"],
        ["域門疆(封鎖對手一項能力20回合)", "Domain Expansion (Block one opponent ability 20 turns)"],
        ["七海的鉈刀(七海)", "Nanami's Knife"],
        ["乙骨的武士刀(乙骨)", "Okkotsu's Katana"],
        ["性轉藥水", "Gender Swap Potion"],
        ["匕首", "Dagger"],
        ["小刀", "Small Knife"],
        ["飛刀", "Flying Knife"],
        ["天鎖斬月", "Tensa Zangetsu"],
        ["拳套", "Boxing Gloves"],
        ["甩棍", "Tonfa"],
        ["雙刀流", "Dual Wield"],
        ["三刀流", "Triple Wield"],
        ["神器劍", "Divine Sword"],
        ["雙槍", "Dual Pistols"],
        ["烏茲", "Uzi"],
        ["RPG", "RPG"],
        ["噴子", "Shotgun"],
        ["雙節棍", "Nunchaku"],
        ["神之斧", "Divine Axe"],
        ["十字弩", "Crossbow"],
        ["卍", "卍"],
        ["斬魄刀", "Zanpakuto"],
        ["求道玉", "Kyardama"],
        ["信夫的拳頭", "Nobuta's Fist"],
        ["噴火器", "Flamethrower"],
        ["手炮", "Hand Cannon"],
        ["朗基努斯之槍", "Spear of Longinus"],
        ["盾牌", "Shield"],
        ["武士刀", "Katana"],
        ["天逆牟", "Ame-no-Murakumo"],
        ["弓", "Bow"],
    ],
    SummonPool: [
        ["黑洞(只能吸東西或人,每個黑洞存在一回合(共五次))", "Black Hole (Can only absorb things/people, one turn each, 5 total uses)"],
        ["靈鹿", "Spirit Deer"],
        ["聖誕阿公的雪橇跟坐騎", "Santa's Sleigh and Mount"],
        ["韓的麥卡倫", "Han's McLaren"],
        ["信夫的西瓜", "Nobuta's Watermelon"],
        ["精靈", "Elf"],
        ["魔法書", "Magic Book"],
        ["里香(十回合召喚一次,共持續三回合)(與乙骨優太搭配能變為完全體)", "Rika (Summon once per 10 turns, lasts 3 turns)(Full power with Okkotsu)"],
        ["模仿者的面具(模仿對手一個能力三回合兩次)", "Mimic Mask (Mimic opponent ability 3 turns, 2 uses)"],
        ["太陽龍", "Sun Dragon"],
        ["波奇塔", "Pochita"],
        ["九喇嘛", "Kurama"],
        ["傳奇寶相", "Legend Guardian"],
        ["日蝕龍", "Eclipse Dragon"],
        ["月亮龍", "Moon Dragon"],
        ["中國龍", "Chinese Dragon"],
        ["狗勾", "Dog"],
        ["蜜蜂龍", "Bee Dragon"],
        ["惡靈", "Evil Spirit"],
        ["女朋友", "Girlfriend"],
        ["傳送門的傳送槍", "Portal Gun"],
        ["恐龍狗", "Dino Dog"],
        ["怪獸:哥吉拉", "Monster: Godzilla"],
        ["怪獸:基多拉", "Monster: Ghidorah"],
    ],
};

function drawHand(lang) {
    const draw = (pool) => {
        const c = pool[Math.floor(Math.random() * pool.length)];
        return lang === 'en' ? (c[1] || c[0]) : (c[0] || c[1]);
    };
    return {
        race: draw(cardPools.racePool),
        weapon: draw(cardPools.WeapenPool),
        abilities: [draw(cardPools.pool), draw(cardPools.pool), draw(cardPools.pool)],
        entity: draw(cardPools.SummonPool),
    };
}

function handler(req, res) {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
    if (req.method === 'OPTIONS') { res.status(200).end(); return; }
    if (req.method !== 'GET') { res.status(405).json({ error: 'Method not allowed' }); return; }
    const lang = req.query.lang || 'en';
    res.status(200).json({ hand: drawHand(lang), lang });
}

module.exports = handler;